# Generated by Django 3.2.2 on 2021-05-13 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_food_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='total_proteins',
            new_name='total_protein',
        ),
    ]
