# Generated by Django 3.2.3 on 2021-06-24 12:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_workout_video_url'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToDoList',
            new_name='Task',
        ),
    ]
