# Generated by Django 3.2.6 on 2021-08-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_likes',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
