# Generated by Django 3.2.6 on 2021-08-29 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_customer_profile_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_followers',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='profile_following',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
