# Generated by Django 3.2.6 on 2021-08-13 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20210813_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='facebook_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='github_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='instagram_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='twitter_link',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
