# Generated by Django 3.2.6 on 2021-08-13 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20210813_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='facebook_link',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='github_link',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='instagram_link',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='twitter_link',
        ),
    ]
