# Generated by Django 3.2.6 on 2021-08-14 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20210813_2032'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='public',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='total_calories',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='total_carbs',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='total_fat',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='total_protein',
        ),
        migrations.RemoveField(
            model_name='food',
            name='category',
        ),
    ]
