# Generated by Django 3.2.6 on 2021-08-15 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210814_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='city',
            field=models.CharField(default='No Information...', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='country',
            field=models.CharField(default='No Information...', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='facebook',
            field=models.CharField(default='No Information...', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='github',
            field=models.CharField(default='No Information...', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='instagram',
            field=models.CharField(default='No Information...', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='job',
            field=models.CharField(default='No Information...', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='mobile_number',
            field=models.CharField(default='No Information...', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(default='No Information...', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='profile_picture',
            field=models.ImageField(default='default_profile_picture.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(default='No Information...', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='twitter',
            field=models.CharField(default='No Information...', max_length=100),
        ),
        migrations.AlterField(
            model_name='customer',
            name='website_link',
            field=models.CharField(default='No Information...', max_length=100),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default='No Information...'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='description',
            field=models.TextField(default='No Information...'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='exercises',
            field=models.TextField(default='No Information...'),
        ),
        migrations.AlterField(
            model_name='workout',
            name='workout_image',
            field=models.ImageField(default='default_workout_image.png', upload_to=''),
        ),
    ]
