# Generated by Django 3.2.6 on 2021-08-25 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20210815_2305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='food',
            old_name='date_eaten',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='food',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
