# Generated by Django 3.1.3 on 2021-02-22 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='savedInProfile',
        ),
    ]
