# Generated by Django 3.1.3 on 2021-03-04 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0003_workout_is_approved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='image',
            field=models.URLField(max_length=250),
        ),
    ]
